In [5]:
import numpy as np
import pandas as pd

In [5]:
x=np.array([1,2,3,4])  # here a list is passed in array function
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>

In [16]:
x=np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [6]:
y=[1,2,3,4 ]  # list 
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>

In [19]:
# for loop
l = []
for i in range(1,5):
    inp=input('Enter values: ')
    l.append(inp)

print('array',l)

Enter values:  1
Enter values:  2
Enter values:  3
Enter values:  4

array ['1', '2', '3', '4']

In [22]:
# for loop
l = []
for i in range(1,5):
    inp=int(input('Enter values: '))
    l.append(inp)

print('array',np.array(l))

Enter values:  1
Enter values:  2
Enter values:  3
Enter values:  4

array [1 2 3 4]

In [24]:
# to find dimension in array
y=[1,2,3,4 ]

print('dimension is: ', np.array(y).ndim)

dimension is:  1

In [35]:
#2 dimensional array
ar2 = np.array([[1,2,3,4],[11,22,33,44]])

print('array is : ', ar2)

print('\n array dimension is : ', ar2.ndim)

array is :  [[ 1  2  3  4]
 [11 22 33 44]]

 array dimension is :  2

# Special type of Arrays
- filled with specific values

***zeros***

In [42]:
zero1_ = np.zeros(4)
print('1D Zeros : ', zero1_)
print()
zero2_ = np.zeros((3,4))
print( zero2_)

1D Zeros :  [0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

***One***

In [6]:
d=np.array([1,2,3,4,5])
print(d)

[1 2 3 4 5]

In [7]:
df=pd.DataFrame(d)

In [10]:
df

   0
0  1
1  2
2  3
3  4
4  5

In [15]:
d1=np.array([[1,2,3,4], [11,22,33,44],[111,222,333,444]])
d1

array([[  1,   2,   3,   4],
       [ 11,  22,  33,  44],
       [111, 222, 333, 444]])

In [16]:
print(d1)

[[  1   2   3   4]
 [ 11  22  33  44]
 [111 222 333 444]]

In [25]:
df1=pd.DataFrame(d1, columns=['a','b','c','d'], index=['r1','r2','r3'])
df1['new']=[77,88,99]
df1

      a    b    c    d  new
r1    1    2    3    4   77
r2   11   22   33   44   88
r3  111  222  333  444   99