Pandas Example

In [1]:
 l=[1,2, 4, 5,67]
l

[1, 2, 4, 5, 67]

In [2]:
import numpy as np
import pandas as pd

In [3]:
l=[1,2, 4, 5,67]
l

[1, 2, 4, 5, 67]

In [5]:
c= np.array(l)

In [6]:
c

array([ 1,  2,  4,  5, 67])

In [7]:
d= pd.Series(l)
d

0     1
1     2
2     4
3     5
4    67
dtype: int64

In [10]:
d+10

0    11
1    12
2    14
3    15
4    77
dtype: int64

In [11]:
c+10

array([11, 12, 14, 15, 77])

In [14]:
d= pd.Series(l, index=['a','b','c','d','e'])
d

a     1
b     2
c     4
d     5
e    67
dtype: int64

In [16]:
d= pd.Series(l, index=range(len(l)))
d

0     1
1     2
2     4
3     5
4    67
dtype: int64

In [17]:
g= {'a': 123, 'b':345, 'c':657}
g

{'a': 123, 'b': 345, 'c': 657}

In [18]:
f=pd.Series(g)
f

a    123
b    345
c    657
dtype: int64

In [8]:
h= {'a': [123], 'b':[345], 'c':[657]}
j= pd.DataFrame(h)
j

     a    b    c
0  123  345  657

In [9]:
h= {'a': 123, 'b':345, 'c':657}
j= pd.DataFrame(h, index=[0])
j

     a    b    c
0  123  345  657

In [13]:
print(pd.DataFrame([[12, 34, 56, 78],[43, 65, 76,87]], columns=['a','b','c','d'], index=['r1','r2']))

     a   b   c   d
r1  12  34  56  78
r2  43  65  76  87

#Create dataframe using 2D array

In [15]:
ar_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(ar_2d)

[[1 2 3 4]
 [5 6 7 8]]

In [16]:
df1=pd.DataFrame(ar_2d, columns=['a','b','c','d'])
df1['serial_no']=np.arange(16,18)
df1.set_index('serial_no')

           a  b  c  d
serial_no
16         1  2  3  4
17         5  6  7  8

# df

In [17]:
df1.shape

(2, 5)

In [18]:
type(df1)

pandas.core.frame.DataFrame

In [19]:
type(ar_2d)

numpy.ndarray

In [20]:
df = pd.DataFrame({'Age':[25,23,56,86,78,98], 'Salary':[120000, 145000, 856300, 564688, 632363, 756214], 'Gender':['M','F','F','M','M','F']})
df

   Age  Salary Gender
0   25  120000      M
1   23  145000      F
2   56  856300      F
3   86  564688      M
4   78  632363      M
5   98  756214      F

In [21]:
df.set_index('Gender', inplace=True)
df

        Age  Salary
Gender
M        25  120000
F        23  145000
F        56  856300
M        86  564688
M        78  632363
F        98  756214

In [22]:
df.loc['M']

        Age  Salary
Gender
M        25  120000
M        86  564688
M        78  632363

**Selecting/extracting data**

In [24]:
df = pd.DataFrame({'Age':[25,23,56,86,78,98], 'Salary':[120000, 145000, 856300, 564688, 632363, 756214], 'Gender':['M','F','F','M','M','F']})
df

   Age  Salary Gender
0   25  120000      M
1   23  145000      F
2   56  856300      F
3   86  564688      M
4   78  632363      M
5   98  756214      F

In [25]:
df.loc[2]

Age           56
Salary    856300
Gender         F
Name: 2, dtype: object

**selction based on slicing**

In [27]:
df.loc[0:4:2]

   Age  Salary Gender
0   25  120000      M
2   56  856300      F
4   78  632363      M

**selction w/o slicing**

In [77]:
df.loc[[0, 2, 4]]

   Age  Salary Gender
0   25  120000      M
2   56  856300      F
4   78  632363      M

**extract single column**

In [28]:
df.loc[:,'Salary']

0    120000
1    145000
2    856300
3    564688
4    632363
5    756214
Name: Salary, dtype: int64

**extract multiple columns with/without slicing**

In [32]:
df.loc[:,'Age':'Gender']

   Age  Salary Gender
0   25  120000      M
1   23  145000      F
2   56  856300      F
3   86  564688      M
4   78  632363      M
5   98  756214      F

In [33]:
df.loc[:,['Age','Gender']]

   Age Gender
0   25      M
1   23      F
2   56      F
3   86      M
4   78      M
5   98      F

**extract selected rows and selected columns**

In [34]:
df.loc[4,['Age','Gender']]

Age       78
Gender     M
Name: 4, dtype: object

**USE OF iLOC**

In [35]:
df

   Age  Salary Gender
0   25  120000      M
1   23  145000      F
2   56  856300      F
3   86  564688      M
4   78  632363      M
5   98  756214      F

In [36]:
df.iloc[-1:-3,:]

Empty DataFrame
Columns: [Age, Salary, Gender]
Index: []

**reset index**

In [37]:
df.set_index('Gender', inplace=True)

In [95]:
df

        Age  Salary
Gender
M        25  120000
F        23  145000
F        56  856300
M        86  564688
M        78  632363
F        98  756214

In [38]:
df.reset_index()

  Gender  Age  Salary
0      M   25  120000
1      F   23  145000
2      F   56  856300
3      M   86  564688
4      M   78  632363
5      F   98  756214

**drop single row**

In [39]:
df= df.drop(index=['M'])
df

        Age  Salary
Gender
F        23  145000
F        56  856300
F        98  756214

In [40]:
df = pd.DataFrame({'Age':[25,23,56,86,78,98], 'Salary':[120000, 145000, 856300, 564688, 632363, 756214], 'Gender':['M','F','F','M','M','F']})
df

   Age  Salary Gender
0   25  120000      M
1   23  145000      F
2   56  856300      F
3   86  564688      M
4   78  632363      M
5   98  756214      F

In [41]:
df=df.drop(index=[2,3])
df

   Age  Salary Gender
0   25  120000      M
1   23  145000      F
4   78  632363      M
5   98  756214      F

In [117]:
df

   Age  Salary Gender
0   25  120000      M
1   23  145000      F
4   78  632363      M
5   98  756214      F

In [42]:
df=df.drop([1])

In [43]:
df

   Age  Salary Gender
0   25  120000      M
4   78  632363      M
5   98  756214      F

In [46]:
df=df.drop(index=range(0,5))
df

   Age  Salary Gender
5   98  756214      F

In [127]:
df

   Age  Salary Gender
0   25  120000      M
4   78  632363      M
5   98  756214      F

In [47]:
df = pd.DataFrame({'Age':[25,23,56,86,78,98], 'Salary':[120000, 145000, 856300, 564688, 632363, 756214], 'Gender':['M','F','F','M','M','F']})
df

   Age  Salary Gender
0   25  120000      M
1   23  145000      F
2   56  856300      F
3   86  564688      M
4   78  632363      M
5   98  756214      F

In [48]:
df= df.drop(index=range(2,5))
df

   Age  Salary Gender
0   25  120000      M
1   23  145000      F
5   98  756214      F

In [55]:
 df = pd.DataFrame({'Age':[25,23,56,86,78,98], 'Salary':[120000, 145000, 856300, 564688, 632363, 756214], 'Gender':['M','F','F','M','M','F']})
df

   Age  Salary Gender
0   25  120000      M
1   23  145000      F
2   56  856300      F
3   86  564688      M
4   78  632363      M
5   98  756214      F

**drop a column**

In [50]:
df.drop(columns='Age', inplace = True)

In [51]:
df

   Salary Gender
0  120000      M
1  145000      F
2  856300      F
3  564688      M
4  632363      M
5  756214      F

In [52]:
df.drop(columns=['Salary','Gender'], inplace=True)

In [53]:
df

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]

**sort values**

In [56]:
df.sort_values(by='Age')

   Age  Salary Gender
1   23  145000      F
0   25  120000      M
2   56  856300      F
4   78  632363      M
3   86  564688      M
5   98  756214      F

In [57]:
#sorting in descending order
df.sort_values(by='Age', ascending=False)

   Age  Salary Gender
5   98  756214      F
3   86  564688      M
4   78  632363      M
2   56  856300      F
0   25  120000      M
1   23  145000      F

**Combing Dataframes**

In [58]:
df1=pd.DataFrame({'City':['Mumbai','Delhi','Banglore','Hydrabad'], 'Temperature':[32,45,40,36]})
df1

       City  Temperature
0    Mumbai           32
1     Delhi           45
2  Banglore           40
3  Hydrabad           36

In [59]:
df2=pd.DataFrame({'City':['Delhi','Mumbai','Banglore','Chennai'], 'Humidity':[68,65,75,70]})
df2

       City  Humidity
0     Delhi        68
1    Mumbai        65
2  Banglore        75
3   Chennai        70

**Concatanation**

In [160]:
df3=pd.concat([df1,df2], axis=1)

In [161]:
df3

       City  Temperature      City  Humidity
0    Mumbai           32     Delhi        68
1     Delhi           45    Mumbai        65
2  Banglore           40  Banglore        75
3  Hydrabad           36   Chennai        70

In [60]:
df4=pd.concat([df1,df2],axis=0, ignore_index=True)
df4

       City  Temperature  Humidity
0    Mumbai         32.0       NaN
1     Delhi         45.0       NaN
2  Banglore         40.0       NaN
3  Hydrabad         36.0       NaN
4     Delhi          NaN      68.0
5    Mumbai          NaN      65.0
6  Banglore          NaN      75.0
7   Chennai          NaN      70.0

**Merging of Dataframes**

In [62]:
pd.merge(df1,df2, on='City', how='outer')

       City  Temperature  Humidity
0  Banglore         40.0      75.0
1   Chennai          NaN      70.0
2     Delhi         45.0      68.0
3  Hydrabad         36.0       NaN
4    Mumbai         32.0      65.0

**display full data**

In [78]:
## use of display.max_rows
import pandas as pd
df=pd.read_csv('C:\\Users\\yadav\\Downloads\\Jupyter\\Datasets\\imdb_top_1000.csv')
df.head()

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"2,83,41,469"
1,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"13,49,66,411"
2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"53,48,58,444"
3,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"5,73,00,000"
4,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"43,60,000"

In [76]:
pd.set_option('display.max_rows', None)

In [77]:
df

                                          Series_Title  Released_Year  \
0                             The Shawshank Redemption           1994
1                                        The Godfather           1972
2                                      The Dark Knight           2008
3                               The Godfather: Part II           1974
4                                         12 Angry Men           1957
5        The Lord of the Rings: The Return of the King           2003
6                                         Pulp Fiction           1994
7                                     Schindler's List           1993
8                                            Inception           2010
9                                           Fight Club           1999
10   The Lord of the Rings: The Fellowship of the Ring           2001
11                                        Forrest Gump           1994
12                     Il buono, il brutto, il cattivo           1966
13               The Lord of the Rings: The Two Towers           2002
14                                          The Matrix           1999
15                                          Goodfellas           1990
16      Star Wars: Episode V - The Empire Strikes Back           1980
17                     One Flew Over the Cuckoo's Nest           1975
18                                            Hamilton           2020
19                                        Gisaengchung           2019
20                                     Soorarai Pottru           2020
21                                        Interstellar           2014
22                                      Cidade de Deus           2002
23                       Sen to Chihiro no kamikakushi           2001
24                                 Saving Private Ryan           1998
25                                      The Green Mile           1999
26                                     La vita è bella           1997
27                                               Se7en           1995
28                            The Silence of the Lambs           1991
29                                           Star Wars           1977
30                                             Seppuku           1962
31                                Shichinin no samurai           1954
32                               It's a Wonderful Life           1946
33                                               Joker           2019
34                                            Whiplash           2014
35                                    The Intouchables           2011
36                                        The Prestige           2006
37                                        The Departed           2006
38                                         The Pianist           2002
39                                           Gladiator           2000
40                                  American History X           1998
41                                  The Usual Suspects           1995
42                                                Léon           1994
43                                       The Lion King           1994
44                          Terminator 2: Judgment Day           1991
45                               Nuovo Cinema Paradiso           1988
46                                      Hotaru no haka           1988
47                                  Back to the Future           1985
48                        Once Upon a Time in the West           1968
49                                              Psycho           1960
50                                          Casablanca           1942
51                                        Modern Times           1936
52                                         City Lights           1931
53                                          Capharnaüm           2018
54                           Ayla: The Daughter of War           2017
55                                        Vikram Vedha           2017
56                                      Kimi no na wa.           2016
57                                              Dangal           2016
58                   Spider-Man: Into the Spider-Verse           2018
59                                   Avengers: Endgame           2019
60                              Avengers: Infinity War           2018
61                                                Coco           2017
62                                    Django Unchained           2012
63                               The Dark Knight Rises           2012
64                                            3 Idiots           2009
65                                    Taare Zameen Par           2007
66                                              WALL·E           2008
67                                 The Lives of Others           2006
68                                            Oldeuboi           2003
69                                             Memento           2000
70                                       Mononoke-hime           1997
71                         Once Upon a Time in America           1984
72                             Raiders of the Lost Ark           1981
73                                         The Shining           1980
74                                      Apocalypse Now           1979
75                                               Alien           1979
76                                               Anand           1971
77                                   Tengoku to jigoku           1963
78   Dr. Strangelove or: How I Learned to Stop Worr...           1964
79                         Witness for the Prosecution           1957
80                                      Paths of Glory           1957
81                                         Rear Window           1954
82                                        Sunset Blvd.           1950
83                                  The Great Dictator           1940
84                                                1917           2019
85                                             Tumbbad           2018
86                                           Andhadhun           2018
87                                            Drishyam           2013
88                                              Jagten           2012
89                             Jodaeiye Nader az Simin           2011
90                                           Incendies           2010
91                                Miracle in cell NO.7           2019
92                                      Babam ve Oglum           2005
93                                Inglourious Basterds           2009
94               Eternal Sunshine of the Spotless Mind           2004
95                                              Amélie           2001
96                                              Snatch           2000
97                                 Requiem for a Dream           2000
98                                     American Beauty           1999
99                                   Good Will Hunting           1997
100                                  Bacheha-Ye aseman           1997
101                                          Toy Story           1995
102                                         Braveheart           1995
103                                     Reservoir Dogs           1992
104                                  Full Metal Jacket           1987
105                                       Idi i smotri           1985
106                                             Aliens           1986
107                                            Amadeus           1984
108                                           Scarface           1983
109         Star Wars: Episode VI - Return of the Jedi           1983
110                                           Das Boot           1981
111                                        Taxi Driver           1976
112                                          The Sting           1973
113                                 A Clockwork Orange           1971
114                              2001: A Space Odyssey           1968
115                         Per qualche dollaro in più           1965
116                                 Lawrence of Arabia           1962
117                                      The Apartment           1960
118                                 North by Northwest           1959
119                                            Vertigo           1958
120                                Singin' in the Rain           1952
121                                              Ikiru           1952
122                                Ladri di biciclette           1948
123                                   Double Indemnity           1944
124                                       Citizen Kane           1941
125                  M - Eine Stadt sucht einen Mörder           1931
126                                         Metropolis           1927
127                                            The Kid           1921
128                                         Chhichhore           2019
129                           Uri: The Surgical Strike           2018
130                                   K.G.F: Chapter 1           2018
131                                         Green Book           2018
132          Three Billboards Outside Ebbing, Missouri           2017
133                                             Talvar           2015
134                        Baahubali 2: The Conclusion           2017
135                                              Klaus           2019
136                                           Drishyam           2015
137                                              Queen           2013
138                                        Mandariinid           2013
139                                 Bhaag Milkha Bhaag           2013
140                                 Gangs of Wasseypur           2012
141                                              Udaan           2010
142                                   Paan Singh Tomar           2012
143                             El secreto de sus ojos           2009
144                                            Warrior           2011
145                                     Shutter Island           2010
146                                                 Up           2009
147                            The Wolf of Wall Street           2013
148                                     Chak De! India           2007
149                                There Will Be Blood           2007
150                                    Pan's Labyrinth           2006
151                                        Toy Story 3           2010
152                                     V for Vendetta           2005
153                                    Rang De Basanti           2006
154                                              Black           2005
155                                      Batman Begins           2005
156                             Swades: We, the People           2004
157                                      Der Untergang           2004
158                               Hauru no ugoku shiro           2004
159                                   A Beautiful Mind           2001
160                                         Hera Pheri           2000
161                Lock, Stock and Two Smoking Barrels           1998
162                                  L.A. Confidential           1997
163                                             Eskiya           1996
164                                               Heat           1995
165                                             Casino           1995
166                                    Andaz Apna Apna           1994
167                                         Unforgiven           1992
168                 Indiana Jones and the Last Crusade           1989
169                                     Dom za vesanje           1988
170                                   Tonari no Totoro           1988
171                                           Die Hard           1988
172                                                Ran           1985
173                                        Raging Bull           1980
174                                            Stalker           1979
175                                        Höstsonaten           1978
176                                        The Message           1976
177                                             Sholay           1975
178                    Monty Python and the Holy Grail           1975
179                                   The Great Escape           1963
180                              To Kill a Mockingbird           1962
181                                            Yôjinbô           1961
182                              Judgment at Nuremberg           1961
183                                   Some Like It Hot           1959
184                                    Smultronstället           1957
185                                Det sjunde inseglet           1957
186                          Du rififi chez les hommes           1955
187                                  Dial M for Murder           1954
188                                   Tôkyô monogatari           1953
189                                           Rashômon           1950
190                                      All About Eve           1950
191                   The Treasure of the Sierra Madre           1948
192                                 To Be or Not to Be           1942
193                                      The Gold Rush           1925
194                                       Sherlock Jr.           1924
195                  Portrait de la jeune fille en feu           2019
196                                               Pink           2016
197                                     Koe no katachi           2016
198                                       Contratiempo           2016
199                                          Ah-ga-ssi           2016
200                                              Mommy           2014
201                                             Haider           2014
202                                              Logan           2017
203                                               Room           2015
204                                   Relatos salvajes           2014
205                                               Soul           2020
206                                         Kis Uykusu           2014
207                                                 PK           2014
208                                    OMG: Oh My God!           2012
209                           The Grand Budapest Hotel           2014
210                                          Gone Girl           2014
211                        Ôkami kodomo no Ame to Yuki           2012
212                                      Hacksaw Ridge           2016
213                                         Inside Out           2015
214                                             Barfi!           2012
215                                   12 Years a Slave           2013
216                                               Rush           2013
217                                     Ford v Ferrari           2019
218                                          Spotlight           2015
219                                    Song of the Sea           2014
220                                            Kahaani           2012
221                           Zindagi Na Milegi Dobara           2011
222                                          Prisoners           2013
223                                 Mad Max: Fury Road           2015
224                                        A Wednesday           2008
225                                        Gran Torino           2008
226       Harry Potter and the Deathly Hallows: Part 2           2011
227                                          Okuribito           2008
228                                Hachi: A Dog's Tale           2009
229                                       Mary and Max           2009
230                           How to Train Your Dragon           2010
231                                      Into the Wild           2007
232                             No Country for Old Men           2007
233                               Lage Raho Munna Bhai           2006
234                                Million Dollar Baby           2004
235                                       Hotel Rwanda           2004
236                              Taegukgi hwinalrimyeo           2004
237                                      Before Sunset           2004
238                                Munna Bhai M.B.B.S.           2003
239                                     Salinui chueok           2003
240                                     Dil Chahta Hai           2001
241                                  Kill Bill: Vol. 1           2003
242                                       Finding Nemo           2003
243                                Catch Me If You Can           2002
244                                      Amores perros           2000
245                                     Monsters, Inc.           2001
246  Shin seiki Evangelion Gekijô-ban: Air/Magokoro...           1997
247                  Lagaan: Once Upon a Time in India           2001
248                                    The Sixth Sense           1999
249               La leggenda del pianista sull'oceano           1998
250                                    The Truman Show           1998
251                             Crna macka, beli macor           1998
252                                   The Big Lebowski           1998
253                                   Fa yeung nin wah           2000
254                                      Trainspotting           1996
255                                              Fargo           1996
256                                        Underground           1995
257                                           La haine           1995
258                        Dilwale Dulhania Le Jayenge           1995
259                                     Before Sunrise           1995
260                              Trois couleurs: Rouge           1994
261                                 Chung Hing sam lam           1994
262                                      Jurassic Park           1993
263                          In the Name of the Father           1993
264                                     Ba wang bie ji           1993
265                        Dà hóng denglong gaogao guà           1991
266                                 Dead Poets Society           1989
267                                        Stand by Me           1986
268                                            Platoon           1986
269                                       Paris, Texas           1984
270                           Kaze no tani no Naushika           1984
271                                          The Thing           1982
272                               Pink Floyd: The Wall           1982
273                                       Fitzcarraldo           1982
274                                Fanny och Alexander           1982
275                                       Blade Runner           1982
276                                   The Elephant Man           1980
277                                      Life of Brian           1979
278                                    The Deer Hunter           1978
279                                              Rocky           1976
280                                            Network           1976
281                                       Barry Lyndon           1975
282                                            Zerkalo           1975
283                                          Chinatown           1974

In [79]:
df1=pd.read_excel('C:\\Users\\yadav\\Downloads\\Jupyter\\Datasets\\tips_data.xlsx')
df1

    total_bill   tip     sex smoker   day    time  size
0        21.85  9.73    Male     No  Thur  Dinner     4
1        47.78  7.98  Female    Yes  Thur   Lunch     3
2        37.94  9.46    Male     No   Sat   Lunch     1
3        31.94  9.05    Male    Yes   Fri  Dinner     4
4        12.02  6.38  Female    Yes   Fri  Dinner     6
5        12.02  9.30    Male    Yes  Thur   Lunch     4
6         7.61  1.80  Female    Yes   Sun  Dinner     6
7        43.98  2.76  Female     No   Fri  Dinner     3
8        32.05  1.41  Female     No   Sun   Lunch     6
9        36.86  3.93    Male    Yes   Fri   Lunch     1
10        5.93  4.50    Male    Yes   Sun  Dinner     3
11       48.65  3.44    Male     No   Sat   Lunch     1
12       42.46  8.46    Male    Yes   Sun   Lunch     5
13       14.56  4.21    Male    Yes   Sat  Dinner     2
14       13.18  3.53    Male    Yes   Sat   Lunch     6
15       13.25  5.88    Male     No   Sun   Lunch     2
16       18.69  2.27  Female     No   Sat  Dinner     2
17       28.61  8.22    Male     No  Thur  Dinner     6
18       24.44  1.67  Female    Yes   Sat   Lunch     3
19       18.11  9.88    Male    Yes   Fri   Lunch     5
20       32.53  7.95    Male     No   Sun  Dinner     1
21       11.28  2.79    Male     No  Thur  Dinner     4
22       18.15  1.05  Female     No   Sun  Dinner     1
23       21.49  8.34  Female     No   Fri  Dinner     4
24       25.52  7.36  Female    Yes   Fri   Lunch     1
25       40.33  7.56  Female     No   Fri  Dinner     6
26       13.99  7.94    Male    Yes   Sat  Dinner     5
27       28.14  1.67  Female     No   Sat   Lunch     4
28       31.66  4.23    Male    Yes   Sun  Dinner     3
29        7.09  2.04    Male     No   Sun   Lunch     1
30       32.34  8.77  Female     No  Thur  Dinner     1
31       12.67  6.61  Female     No  Thur  Dinner     4
32        7.93  3.98  Female     No   Sun  Dinner     3
33       47.70  1.57  Female    Yes   Sat   Lunch     3
34       48.45  3.80  Female     No   Fri   Lunch     6
35       41.38  3.93  Female    Yes   Sun  Dinner     6
36       18.71  7.57  Female    Yes  Thur   Lunch     6
37        9.40  6.74  Female    Yes   Sat   Lunch     6
38       35.79  8.98    Male    Yes   Sun   Lunch     6
39       24.81  5.25  Female     No   Sun   Lunch     6
40       10.49  2.08  Female    Yes   Sat   Lunch     5
41       27.28  7.42    Male    Yes   Sun   Lunch     3
42        6.55  7.85  Female    Yes   Sat  Dinner     6
43       45.92  6.05    Male     No   Fri  Dinner     3
44       16.65  7.94    Male     No   Sat   Lunch     3
45       34.81  5.44  Female     No   Sat  Dinner     2
46       19.03  5.70    Male     No   Sat  Dinner     5
47       28.40  4.85    Male    Yes   Sun  Dinner     6
48       29.60  1.23    Male    Yes   Sun  Dinner     1
49       13.32  1.97    Male     No   Sat   Lunch     4

In [10]:
## use of shape, size, columns, keys
df1.shape

(50, 7)

In [11]:
df1.size

350

In [81]:
df1.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [14]:
df1.keys()

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

**Rename Column**

In [15]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  50 non-null     float64
 1   tip         50 non-null     float64
 2   sex         50 non-null     object
 3   smoker      50 non-null     object
 4   day         50 non-null     object
 5   time        50 non-null     object
 6   size        50 non-null     int64
dtypes: float64(2), int64(1), object(4)
memory usage: 2.9+ KB

In [17]:
# use of rename
df1=df1.rename(columns={'sex':'gender','size':'no_of_members'})
df1.keys()

Index(['total_bill', 'tip', 'gender', 'smoker', 'day', 'time',
       'no_of_members'],
      dtype='object')

In [19]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   total_bill     50 non-null     float64
 1   tip            50 non-null     float64
 2   gender         50 non-null     object
 3   smoker         50 non-null     object
 4   day            50 non-null     object
 5   time           50 non-null     object
 6   no_of_members  50 non-null     int64
dtypes: float64(2), int64(1), object(4)
memory usage: 2.9+ KB

**data types of each columns**

In [21]:
df1.dtypes

total_bill       float64
tip              float64
gender            object
smoker            object
day               object
time              object
no_of_members      int64
dtype: object

**check for missing values**

In [26]:
df1.isnull().sum()

total_bill       0
tip              0
gender           0
smoker           0
day              0
time             0
no_of_members    0
dtype: int64

**Extracting/Accessing values**

In [28]:
df1.iloc[[2,3,4],[0,2]]

   total_bill  gender
2       37.94    Male
3       31.94    Male
4       12.02  Female

In [30]:
import numpy as np
df=pd.DataFrame({'X':[1,2,3,np.nan,5]})
df

     X
0  1.0
1  2.0
2  3.0
3  NaN
4  5.0

In [32]:
df.isnull().sum()

X    1
dtype: int64

In [33]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   total_bill     50 non-null     float64
 1   tip            50 non-null     float64
 2   gender         50 non-null     object
 3   smoker         50 non-null     object
 4   day            50 non-null     object
 5   time           50 non-null     object
 6   no_of_members  50 non-null     int64
dtypes: float64(2), int64(1), object(4)
memory usage: 2.9+ KB

In [37]:
df1['gender']

0       Male
1     Female
2       Male
3       Male
4     Female
5       Male
6     Female
7     Female
8     Female
9       Male
10      Male
11      Male
12      Male
13      Male
14      Male
15      Male
16    Female
17      Male
18    Female
19      Male
20      Male
21      Male
22    Female
23    Female
24    Female
25    Female
26      Male
27    Female
28      Male
29      Male
30    Female
31    Female
32    Female
33    Female
34    Female
35    Female
36    Female
37    Female
38      Male
39    Female
40    Female
41      Male
42    Female
43      Male
44      Male
45    Female
46      Male
47      Male
48      Male
49      Male
Name: gender, dtype: object

In [38]:
df1['gender'].shape

(50,)

In [39]:
df1['gender'].size

50

In [40]:
df1['gender'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 50 entries, 0 to 49
Series name: gender
Non-Null Count  Dtype
--------------  -----
50 non-null     object
dtypes: object(1)
memory usage: 532.0+ bytes

**ACCESS OF DATA OF MULTIPLE COLUMNS**

In [41]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   total_bill     50 non-null     float64
 1   tip            50 non-null     float64
 2   gender         50 non-null     object
 3   smoker         50 non-null     object
 4   day            50 non-null     object
 5   time           50 non-null     object
 6   no_of_members  50 non-null     int64
dtypes: float64(2), int64(1), object(4)
memory usage: 2.9+ KB

In [44]:
df1[['tip','smoker','time']]

     tip smoker    time
0   9.73     No  Dinner
1   7.98    Yes   Lunch
2   9.46     No   Lunch
3   9.05    Yes  Dinner
4   6.38    Yes  Dinner
5   9.30    Yes   Lunch
6   1.80    Yes  Dinner
7   2.76     No  Dinner
8   1.41     No   Lunch
9   3.93    Yes   Lunch
10  4.50    Yes  Dinner
11  3.44     No   Lunch
12  8.46    Yes   Lunch
13  4.21    Yes  Dinner
14  3.53    Yes   Lunch
15  5.88     No   Lunch
16  2.27     No  Dinner
17  8.22     No  Dinner
18  1.67    Yes   Lunch
19  9.88    Yes   Lunch
20  7.95     No  Dinner
21  2.79     No  Dinner
22  1.05     No  Dinner
23  8.34     No  Dinner
24  7.36    Yes   Lunch
25  7.56     No  Dinner
26  7.94    Yes  Dinner
27  1.67     No   Lunch
28  4.23    Yes  Dinner
29  2.04     No   Lunch
30  8.77     No  Dinner
31  6.61     No  Dinner
32  3.98     No  Dinner
33  1.57    Yes   Lunch
34  3.80     No   Lunch
35  3.93    Yes  Dinner
36  7.57    Yes   Lunch
37  6.74    Yes   Lunch
38  8.98    Yes   Lunch
39  5.25     No   Lunch
40  2.08    Yes   Lunch
41  7.42    Yes   Lunch
42  7.85    Yes  Dinner
43  6.05     No  Dinner
44  7.94     No   Lunch
45  5.44     No  Dinner
46  5.70     No  Dinner
47  4.85    Yes  Dinner
48  1.23    Yes  Dinner
49  1.97     No   Lunch

In [45]:
df1[['tip','smoker','time']].size

150

**convert pandas series to numpy 1D array using values and to_numpy**

In [48]:
df1[['tip','smoker','time']].to_numpy()

array([[9.73, 'No', 'Dinner'],
       [7.98, 'Yes', 'Lunch'],
       [9.46, 'No', 'Lunch'],
       [9.05, 'Yes', 'Dinner'],
       [6.38, 'Yes', 'Dinner'],
       [9.3, 'Yes', 'Lunch'],
       [1.8, 'Yes', 'Dinner'],
       [2.76, 'No', 'Dinner'],
       [1.41, 'No', 'Lunch'],
       [3.93, 'Yes', 'Lunch'],
       [4.5, 'Yes', 'Dinner'],
       [3.44, 'No', 'Lunch'],
       [8.46, 'Yes', 'Lunch'],
       [4.21, 'Yes', 'Dinner'],
       [3.53, 'Yes', 'Lunch'],
       [5.88, 'No', 'Lunch'],
       [2.27, 'No', 'Dinner'],
       [8.22, 'No', 'Dinner'],
       [1.67, 'Yes', 'Lunch'],
       [9.88, 'Yes', 'Lunch'],
       [7.95, 'No', 'Dinner'],
       [2.79, 'No', 'Dinner'],
       [1.05, 'No', 'Dinner'],
       [8.34, 'No', 'Dinner'],
       [7.36, 'Yes', 'Lunch'],
       [7.56, 'No', 'Dinner'],
       [7.94, 'Yes', 'Dinner'],
       [1.67, 'No', 'Lunch'],
       [4.23, 'Yes', 'Dinner'],
       [2.04, 'No', 'Lunch'],
       [8.77, 'No', 'Dinner'],
       [6.61, 'No', 'Dinner'],
       [3.98, 'No', 'Dinner'],
       [1.57, 'Yes', 'Lunch'],
       [3.8, 'No', 'Lunch'],
       [3.93, 'Yes', 'Dinner'],
       [7.57, 'Yes', 'Lunch'],
       [6.74, 'Yes', 'Lunch'],
       [8.98, 'Yes', 'Lunch'],
       [5.25, 'No', 'Lunch'],
       [2.08, 'Yes', 'Lunch'],
       [7.42, 'Yes', 'Lunch'],
       [7.85, 'Yes', 'Dinner'],
       [6.05, 'No', 'Dinner'],
       [7.94, 'No', 'Lunch'],
       [5.44, 'No', 'Dinner'],
       [5.7, 'No', 'Dinner'],
       [4.85, 'Yes', 'Dinner'],
       [1.23, 'Yes', 'Dinner'],
       [1.97, 'No', 'Lunch']], dtype=object)

In [56]:
df1[['tip','smoker','time']].values

array([[9.73, 'No', 'Dinner'],
       [7.98, 'Yes', 'Lunch'],
       [9.46, 'No', 'Lunch'],
       [9.05, 'Yes', 'Dinner'],
       [6.38, 'Yes', 'Dinner'],
       [9.3, 'Yes', 'Lunch'],
       [1.8, 'Yes', 'Dinner'],
       [2.76, 'No', 'Dinner'],
       [1.41, 'No', 'Lunch'],
       [3.93, 'Yes', 'Lunch'],
       [4.5, 'Yes', 'Dinner'],
       [3.44, 'No', 'Lunch'],
       [8.46, 'Yes', 'Lunch'],
       [4.21, 'Yes', 'Dinner'],
       [3.53, 'Yes', 'Lunch'],
       [5.88, 'No', 'Lunch'],
       [2.27, 'No', 'Dinner'],
       [8.22, 'No', 'Dinner'],
       [1.67, 'Yes', 'Lunch'],
       [9.88, 'Yes', 'Lunch'],
       [7.95, 'No', 'Dinner'],
       [2.79, 'No', 'Dinner'],
       [1.05, 'No', 'Dinner'],
       [8.34, 'No', 'Dinner'],
       [7.36, 'Yes', 'Lunch'],
       [7.56, 'No', 'Dinner'],
       [7.94, 'Yes', 'Dinner'],
       [1.67, 'No', 'Lunch'],
       [4.23, 'Yes', 'Dinner'],
       [2.04, 'No', 'Lunch'],
       [8.77, 'No', 'Dinner'],
       [6.61, 'No', 'Dinner'],
       [3.98, 'No', 'Dinner'],
       [1.57, 'Yes', 'Lunch'],
       [3.8, 'No', 'Lunch'],
       [3.93, 'Yes', 'Dinner'],
       [7.57, 'Yes', 'Lunch'],
       [6.74, 'Yes', 'Lunch'],
       [8.98, 'Yes', 'Lunch'],
       [5.25, 'No', 'Lunch'],
       [2.08, 'Yes', 'Lunch'],
       [7.42, 'Yes', 'Lunch'],
       [7.85, 'Yes', 'Dinner'],
       [6.05, 'No', 'Dinner'],
       [7.94, 'No', 'Lunch'],
       [5.44, 'No', 'Dinner'],
       [5.7, 'No', 'Dinner'],
       [4.85, 'Yes', 'Dinner'],
       [1.23, 'Yes', 'Dinner'],
       [1.97, 'No', 'Lunch']], dtype=object)

**convert pandas dataframe to numpy 2D array**

In [57]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   total_bill     50 non-null     float64
 1   tip            50 non-null     float64
 2   gender         50 non-null     object
 3   smoker         50 non-null     object
 4   day            50 non-null     object
 5   time           50 non-null     object
 6   no_of_members  50 non-null     int64
dtypes: float64(2), int64(1), object(4)
memory usage: 2.9+ KB

In [62]:
# check with internet
df1[['day']].to_numpy().ravel()

array(['Thur', 'Thur', 'Sat', 'Fri', 'Fri', 'Thur', 'Sun', 'Fri', 'Sun',
       'Fri', 'Sun', 'Sat', 'Sun', 'Sat', 'Sat', 'Sun', 'Sat', 'Thur',
       'Sat', 'Fri', 'Sun', 'Thur', 'Sun', 'Fri', 'Fri', 'Fri', 'Sat',
       'Sat', 'Sun', 'Sun', 'Thur', 'Thur', 'Sun', 'Sat', 'Fri', 'Sun',
       'Thur', 'Sat', 'Sun', 'Sun', 'Sat', 'Sun', 'Sat', 'Fri', 'Sat',
       'Sat', 'Sat', 'Sun', 'Sun', 'Sat'], dtype=object)

**FILTERING**

In [66]:
# using 1 condition
len(df1[df1['tip']>7])

19

In [72]:
# USING MULTIPLE CONDITIONS
df1[(df1['tip']>7) & (df1['gender']=='Female')]

    total_bill   tip  gender smoker   day    time  no_of_members
1        47.78  7.98  Female    Yes  Thur   Lunch              3
23       21.49  8.34  Female     No   Fri  Dinner              4
24       25.52  7.36  Female    Yes   Fri   Lunch              1
25       40.33  7.56  Female     No   Fri  Dinner              6
30       32.34  8.77  Female     No  Thur  Dinner              1
36       18.71  7.57  Female    Yes  Thur   Lunch              6
42        6.55  7.85  Female    Yes   Sat  Dinner              6

In [73]:
# find the length using len or shape
len(df1[(df1['tip']>7) & (df1['gender']=='Female')])

7

In [74]:
df1[(df1['tip']>7) & (df1['gender']=='Female')].shape[0]

7

In [77]:
## CROSSTAB
pd.crosstab(df1['gender'], df1['day'])

day     Fri  Sat  Sun  Thur
gender
Female    6    8    6     4
Male      4    8   10     4

**for discrete values**, **to find unique values**

In [80]:
df1['gender'].unique()

array(['Male', 'Female'], dtype=object)

In [81]:
df1['smoker'].unique()

array(['No', 'Yes'], dtype=object)

In [82]:
df1['gender'].value_counts()

gender
Male      26
Female    24
Name: count, dtype: int64

In [84]:
df1['smoker'].value_counts()

smoker
No     25
Yes    25
Name: count, dtype: int64

In [87]:
df1=df1.rename(columns={'gender':'sex'})
df1

    total_bill   tip     sex smoker   day    time  no_of_members
0        21.85  9.73    Male     No  Thur  Dinner              4
1        47.78  7.98  Female    Yes  Thur   Lunch              3
2        37.94  9.46    Male     No   Sat   Lunch              1
3        31.94  9.05    Male    Yes   Fri  Dinner              4
4        12.02  6.38  Female    Yes   Fri  Dinner              6
5        12.02  9.30    Male    Yes  Thur   Lunch              4
6         7.61  1.80  Female    Yes   Sun  Dinner              6
7        43.98  2.76  Female     No   Fri  Dinner              3
8        32.05  1.41  Female     No   Sun   Lunch              6
9        36.86  3.93    Male    Yes   Fri   Lunch              1
10        5.93  4.50    Male    Yes   Sun  Dinner              3
11       48.65  3.44    Male     No   Sat   Lunch              1
12       42.46  8.46    Male    Yes   Sun   Lunch              5
13       14.56  4.21    Male    Yes   Sat  Dinner              2
14       13.18  3.53    Male    Yes   Sat   Lunch              6
15       13.25  5.88    Male     No   Sun   Lunch              2
16       18.69  2.27  Female     No   Sat  Dinner              2
17       28.61  8.22    Male     No  Thur  Dinner              6
18       24.44  1.67  Female    Yes   Sat   Lunch              3
19       18.11  9.88    Male    Yes   Fri   Lunch              5
20       32.53  7.95    Male     No   Sun  Dinner              1
21       11.28  2.79    Male     No  Thur  Dinner              4
22       18.15  1.05  Female     No   Sun  Dinner              1
23       21.49  8.34  Female     No   Fri  Dinner              4
24       25.52  7.36  Female    Yes   Fri   Lunch              1
25       40.33  7.56  Female     No   Fri  Dinner              6
26       13.99  7.94    Male    Yes   Sat  Dinner              5
27       28.14  1.67  Female     No   Sat   Lunch              4
28       31.66  4.23    Male    Yes   Sun  Dinner              3
29        7.09  2.04    Male     No   Sun   Lunch              1
30       32.34  8.77  Female     No  Thur  Dinner              1
31       12.67  6.61  Female     No  Thur  Dinner              4
32        7.93  3.98  Female     No   Sun  Dinner              3
33       47.70  1.57  Female    Yes   Sat   Lunch              3
34       48.45  3.80  Female     No   Fri   Lunch              6
35       41.38  3.93  Female    Yes   Sun  Dinner              6
36       18.71  7.57  Female    Yes  Thur   Lunch              6
37        9.40  6.74  Female    Yes   Sat   Lunch              6
38       35.79  8.98    Male    Yes   Sun   Lunch              6
39       24.81  5.25  Female     No   Sun   Lunch              6
40       10.49  2.08  Female    Yes   Sat   Lunch              5
41       27.28  7.42    Male    Yes   Sun   Lunch              3
42        6.55  7.85  Female    Yes   Sat  Dinner              6
43       45.92  6.05    Male     No   Fri  Dinner              3
44       16.65  7.94    Male     No   Sat   Lunch              3
45       34.81  5.44  Female     No   Sat  Dinner              2
46       19.03  5.70    Male     No   Sat  Dinner              5
47       28.40  4.85    Male    Yes   Sun  Dinner              6
48       29.60  1.23    Male    Yes   Sun  Dinner              1
49       13.32  1.97    Male     No   Sat   Lunch              4

In [88]:
# again rename to gender from sex
df1=df1.rename(columns={'sex':'gender'})
df1

    total_bill   tip  gender smoker   day    time  no_of_members
0        21.85  9.73    Male     No  Thur  Dinner              4
1        47.78  7.98  Female    Yes  Thur   Lunch              3
2        37.94  9.46    Male     No   Sat   Lunch              1
3        31.94  9.05    Male    Yes   Fri  Dinner              4
4        12.02  6.38  Female    Yes   Fri  Dinner              6
5        12.02  9.30    Male    Yes  Thur   Lunch              4
6         7.61  1.80  Female    Yes   Sun  Dinner              6
7        43.98  2.76  Female     No   Fri  Dinner              3
8        32.05  1.41  Female     No   Sun   Lunch              6
9        36.86  3.93    Male    Yes   Fri   Lunch              1
10        5.93  4.50    Male    Yes   Sun  Dinner              3
11       48.65  3.44    Male     No   Sat   Lunch              1
12       42.46  8.46    Male    Yes   Sun   Lunch              5
13       14.56  4.21    Male    Yes   Sat  Dinner              2
14       13.18  3.53    Male    Yes   Sat   Lunch              6
15       13.25  5.88    Male     No   Sun   Lunch              2
16       18.69  2.27  Female     No   Sat  Dinner              2
17       28.61  8.22    Male     No  Thur  Dinner              6
18       24.44  1.67  Female    Yes   Sat   Lunch              3
19       18.11  9.88    Male    Yes   Fri   Lunch              5
20       32.53  7.95    Male     No   Sun  Dinner              1
21       11.28  2.79    Male     No  Thur  Dinner              4
22       18.15  1.05  Female     No   Sun  Dinner              1
23       21.49  8.34  Female     No   Fri  Dinner              4
24       25.52  7.36  Female    Yes   Fri   Lunch              1
25       40.33  7.56  Female     No   Fri  Dinner              6
26       13.99  7.94    Male    Yes   Sat  Dinner              5
27       28.14  1.67  Female     No   Sat   Lunch              4
28       31.66  4.23    Male    Yes   Sun  Dinner              3
29        7.09  2.04    Male     No   Sun   Lunch              1
30       32.34  8.77  Female     No  Thur  Dinner              1
31       12.67  6.61  Female     No  Thur  Dinner              4
32        7.93  3.98  Female     No   Sun  Dinner              3
33       47.70  1.57  Female    Yes   Sat   Lunch              3
34       48.45  3.80  Female     No   Fri   Lunch              6
35       41.38  3.93  Female    Yes   Sun  Dinner              6
36       18.71  7.57  Female    Yes  Thur   Lunch              6
37        9.40  6.74  Female    Yes   Sat   Lunch              6
38       35.79  8.98    Male    Yes   Sun   Lunch              6
39       24.81  5.25  Female     No   Sun   Lunch              6
40       10.49  2.08  Female    Yes   Sat   Lunch              5
41       27.28  7.42    Male    Yes   Sun   Lunch              3
42        6.55  7.85  Female    Yes   Sat  Dinner              6
43       45.92  6.05    Male     No   Fri  Dinner              3
44       16.65  7.94    Male     No   Sat   Lunch              3
45       34.81  5.44  Female     No   Sat  Dinner              2
46       19.03  5.70    Male     No   Sat  Dinner              5
47       28.40  4.85    Male    Yes   Sun  Dinner              6
48       29.60  1.23    Male    Yes   Sun  Dinner              1
49       13.32  1.97    Male     No   Sat   Lunch              4

**reset display to only limited data**

In [93]:
pd.set_option('display.max_rows', 10)

In [94]:
df1

    total_bill   tip  gender smoker   day    time  no_of_members
0        21.85  9.73    Male     No  Thur  Dinner              4
1        47.78  7.98  Female    Yes  Thur   Lunch              3
2        37.94  9.46    Male     No   Sat   Lunch              1
3        31.94  9.05    Male    Yes   Fri  Dinner              4
4        12.02  6.38  Female    Yes   Fri  Dinner              6
..         ...   ...     ...    ...   ...     ...            ...
45       34.81  5.44  Female     No   Sat  Dinner              2
46       19.03  5.70    Male     No   Sat  Dinner              5
47       28.40  4.85    Male    Yes   Sun  Dinner              6
48       29.60  1.23    Male    Yes   Sun  Dinner              1
49       13.32  1.97    Male     No   Sat   Lunch              4

[50 rows x 7 columns]

In [100]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   total_bill     50 non-null     float64
 1   tip            50 non-null     float64
 2   gender         50 non-null     object
 3   smoker         50 non-null     object
 4   day            50 non-null     object
 5   time           50 non-null     object
 6   no_of_members  50 non-null     int64
dtypes: float64(2), int64(1), object(4)
memory usage: 3.1+ KB

**USE OF NUNIQUE TO FIND NO OF UNIQUE VALUES**

In [96]:
df1['time'].unique()

array(['Dinner', 'Lunch'], dtype=object)

In [97]:
df1['time'].unique().shape[0]

2

In [104]:
df1['time'].nunique()

2

**USE OF NORMALIZE**

In [112]:
df1['gender'].value_counts(normalize=True)

gender
Male      0.52
Female    0.48
Name: proportion, dtype: float64

**DISCRETIZATION**

In [105]:
df1['total_bill'].min()

5.93

In [106]:
df1['total_bill'].max()

48.65

In [108]:
df1['bill_category']=pd.cut(df1['total_bill'],
                            bins=[0,10,30,50],
                            labels=['low','moderate','good'])

In [111]:
df1['bill_category'].value_counts()

bill_category
moderate    26
good        18
low          6
Name: count, dtype: int64

**GROUPBY**

In [114]:
df1.groupby('gender')['tip'].mean()

gender
Female    4.743333
Male      6.103077
Name: tip, dtype: float64

In [118]:
pd.crosstab(df1['time'],df1['gender'], margins=True)

gender  Female  Male  All
time
Dinner      13    13   26
Lunch       11    13   24
All         24    26   50